---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory-service-dev
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
