
---
spring:
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

